/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessToken: () => import('#controllers/access_token_controller'),
  Customers: () => import('#controllers/customers_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Payments: () => import('#controllers/payments_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Transactions: () => import('#controllers/transactions_controller'),
}
